import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import { getSortedPostsData } from '../lib/posts';
// import {Avatar, Skeleton} from "@mui/material";
import Avatar from "../src/ui/avatar"

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {/* For variant="text", adjust the height via font-size */}
        <Avatar src="/assests/pika.jpg"></Avatar>
        {/*<Skeleton variant="circular" width={40} height={40} />*/}
        {/*<Skeleton variant="rounded" width={210} height={60} />*/}
        <p className={styles.description}>
          click{' '}
          <Link href="/test1/test">
            <code className={styles.code}>pages/test1/test.js</code>
          </Link>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/shiyiqiaoFE"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Avatar src="/assests/pika.jpg"></Avatar>
        </a>
      </footer>
    </div>
  )
}


